name: Dead code analysis

on:
  workflow_dispatch:
  push:

jobs:
  deadnix:
    name: Deadnix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: cachix/install-nix-action@main
      - uses: cachix/cachix-action@main
        with:
          name: deadnix
      - uses: phucleeuwu/deadnix-action@main
