on: [push]

name: Dead code analysis

jobs:
  deadnix:
    name: Deadnix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          name: deadnix
      - uses: astro/deadnix-action@main
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Deadnix code fix
