name: Dead code analysis

on:
  workflow_dispatch:
  push:

concurrency:
  group: global-lock
  cancel-in-progress: false

jobs:
  deadnix:
    name: Deadnix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: phucisstupid/deadnix-action@main
