name: Statix Linter

on:
  workflow_dispatch:
  push:

concurrency:
  group: global-lock
  cancel-in-progress: false

jobs:
  statix:
    name: Statix Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: phucisstupid/statix-action@main
