name: Statix Linter

on:
  workflow_dispatch:
  push:

jobs:
  statix:
    name: Statix Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v14
        with:
          name: statix
      - uses: phucleeuwu/statix-action@v1
        with:
          commit_message: "Chore: Lint nix code with statix"
